apiVersion: skaffold/v4beta13
kind: Config

manifests:
  rawYaml:
    - ./infra/k8s/*

build:
  local:
    push: false
  artifacts:
    - image: sagarcom853/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"   # watches all .ts files in src
            dest: .
